CREATE SEQUENCE SEQ_GESTAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TBL_GESTAO_ENERGIA (
    ID_CONSUMO INTEGER DEFAULT SEQ_GESTAO.nextval NOT NULL,
    DATA_LEITURA DATE NOT NULL,
    CONSUMO DECIMAL(10,2) NOT NULL


);